### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by capfei** [miksch123/WiniumWebdriver#2]
Is the license for https://www.nuget.org/packages/OpenQA.Selenium.Winium GPL 2.0 or MPL 2.0? The GPL license is included with the NuGet package and the root of this repo, but then I saw that all of the folders have READMEs that state MPL 2.0. Can you clarify which is the correct license?

**Comment by miksch123** [comment]
This repo is running under the same license as the repo I cloned it from: https://github.com/2gis/Winium
Also the only area I changed is the dotnet one where I add a dispose, so it is compatible with selenium version 3.1 at the time.
Hope that helps.

**Comment by capfei** [comment]
Thanks for clarifying that the license is MPL 2.0.
